# Generated by Django 5.1 on 2024-10-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=255)),
                ('about_heading', models.CharField(max_length=255)),
                ('about_text', models.TextField()),
                ('about_img', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_question1', models.CharField(max_length=255)),
                ('faq_answer1', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('pickup', 'Garbage Pickup'), ('residential', 'Residential Waste Sorting Service'), ('industrial', 'Industrial Waste Sorting Service'), ('commercial', 'Commercial Waste Sorting Service'), ('dumpster', 'Dumpster Rental')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.CharField(default='per month', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('features', models.TextField(help_text='Separate features with a comma.')),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='settings',
            name='about_hero',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='contact_hero',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='faq_hero',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='pricing_hero',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='services_hero',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='slider_heading1',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='slider_heading2',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='slider_heading3',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
