# Generated by Django 5.1 on 2024-10-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSS', '0002_about_faq_pricingplan_services_settings_about_hero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='page_type',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='preloader_video',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
