# Generated by Django 5.1 on 2024-10-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AWSS', '0003_settings_page_type_settings_preloader_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='page_type',
        ),
    ]
