# Generated by Django 5.1 on 2024-10-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSS', '0005_pagetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='home_slider1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='home_slider2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='home_slider3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
