# Generated by Django 5.1 on 2024-10-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSS', '0006_alter_settings_favicon_alter_settings_home_slider1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='email',
            field=models.EmailField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_desc',
            field=models.TextField(default='defalt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='location',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='phone',
            field=models.CharField(default=92, max_length=20),
            preserve_default=False,
        ),
    ]
