# Generated by Django 5.1 on 2024-10-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSS', '0007_settings_email_settings_footer_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='facebook',
            field=models.CharField(default='facebook', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='pinterest',
            field=models.CharField(default='pinterest', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='twitter',
            field=models.CharField(default='twitter', max_length=255),
            preserve_default=False,
        ),
    ]
