# Generated by Django 5.1 on 2024-11-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSS', '0009_settings_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='pre_loader_video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
