# Generated by Django 5.1 on 2024-11-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AWSS', '0011_alter_about_about_img_alter_services_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='description',
        ),
    ]
