# Generated by Django 5.1 on 2024-11-06 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AWSS', '0012_remove_services_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about_heading',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_text',
        ),
    ]
