# Generated by Django 5.1 on 2024-11-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSS', '0014_about_about_heading_about_about_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whyjoinus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whyjoinus_title', models.CharField(blank=True, max_length=255, null=True)),
                ('whyjoinus_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('whyjoinus_subheading', models.CharField(max_length=255)),
                ('whyjoinus_desc', models.CharField(max_length=255)),
            ],
        ),
    ]
