# Generated by Django 5.1 on 2024-11-06 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSS', '0015_whyjoinus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whyjoinus',
            options={'verbose_name_plural': 'Why Join Us'},
        ),
        migrations.RenameField(
            model_name='whyjoinus',
            old_name='whyjoinus_desc',
            new_name='heading',
        ),
        migrations.RemoveField(
            model_name='whyjoinus',
            name='whyjoinus_heading',
        ),
        migrations.RemoveField(
            model_name='whyjoinus',
            name='whyjoinus_subheading',
        ),
        migrations.RemoveField(
            model_name='whyjoinus',
            name='whyjoinus_title',
        ),
        migrations.AddField(
            model_name='whyjoinus',
            name='title',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WhyJoinUsSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('why_join_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sections', to='AWSS.whyjoinus')),
            ],
        ),
    ]
