# Generated by Django 5.1 on 2024-11-10 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AWSS', '0017_whyjoinus_image_whyjoinus_number_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='faq_answer1',
            new_name='faq_answer',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='faq_question1',
            new_name='faq_question',
        ),
    ]
