# Generated by Django 5.1 on 2024-12-06 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AWSS', '0019_pricingplan_service_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplan',
            name='service_type',
        ),
    ]
