# Generated by Django 5.1 on 2024-12-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSS', '0020_remove_pricingplan_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField()),
                ('date_published', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
