# Generated by Django 5.1 on 2025-01-15 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSS', '0021_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AWSS.pricingplan'),
            preserve_default=False,
        ),
    ]
